// export { Home as default } from '@/views/SamplePage/SamplePage'
import clsx from 'clsx'
import type { NextPage } from 'next'
import Head from 'next/head'
import { useIntl } from 'react-intl'

export function getServerSideProps(context: any) {
  const { locale } = context
  return {
    props: { locale }
  }
}
interface HopeProps {
  locale: string
}
export const Home: NextPage<HopeProps> = ({ locale }) => {
  const { formatMessage } = useIntl()
  const f = (id: string, value?: string) => formatMessage({ id }, { value })

  const dynamicValue = locale === 'en' ? 'value' : 'مقدار'
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1 className={clsx('text-6xl', 'text-green-600 p-2')}>
          {f('welcome')} <a href='https://nextjs.org'>{f('nextjs')}</a>
        </h1>
        <h2 className='text-3xl'>
          {formatMessage({ id: 'dynamic' }, { value: dynamicValue })}
        </h2>
      </main>
    </div>
  )
}

export default Home
